# Generated by Django 3.1.1 on 2020-10-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
