# Generated by Django 3.1.1 on 2020-09-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visible',
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=1, verbose_name='Черновик'),
        ),
    ]
