# Generated by Django 3.1.1 on 2020-09-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
